[build-system]
requires = ["setuptools>=44.0.0", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "tsc_utils/version.py"
